### ISSUE TITLE
Cat.Js Returns: fetch is not a function

### ISSUE THREAD

**Issue by Manumission247** [Manumission247/ModManager#2]
When running "?cat"
The bot returns error: fetch is not a function

CONSOLE LOG:
`TypeError: fetch is not a function
    at Object.exports.run (C:\ModManager\commands\cat.js:9:26)
    at module.exports (C:\ModManager\events\messageCreate.js:88:15)
    at Client.emit (node:events:390:28)
    at MessageCreateAction.handle (C:\ModManager\node_modules\discord.js\src\client\actions\MessageCreate.js:23:14)
    at Object.module.exports [as MESSAGE_CREATE] (C:\ModManager\node_modules\discord.js\src\client\websocket\handlers\MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (C:\ModManager\node_modules\discord.js\src\client\websocket\WebSocketManager.js:345:31)
    at WebSocketShard.onPacket (C:\ModManager\node_modules\discord.js\src\client\websocket\WebSocketShard.js:443:22)
    at WebSocketShard.onMessage (C:\ModManager\node_modules\discord.js\src\client\websocket\WebSocketShard.js:300:10)
    at WebSocket.onMessage (C:\ModManager\node_modules\ws\lib\event-target.js:132:16)
    at WebSocket.emit (node:events:390:28)`

**Comment by Manumission247** [comment]
Issue was fixed by following the guide:
https://dev.to/isalevine/three-ways-to-retrieve-json-from-the-web-using-node-js-3c88
